UPDATE "Product"
SET "description" =
  CASE
    WHEN "name" = 'Apples' THEN 'Fresh fruit for eating, cooking, or adding to snacks and lunch boxes.'
    WHEN "name" = 'Avocados' THEN 'Creamy fruit used for toast, salads, dips, and simple meals.'
    WHEN "name" = 'Bagels' THEN 'Round bread rolls suited for breakfast, sandwiches, or toasted snacks.'
    WHEN "name" = 'Basic Thobe' THEN 'A simple long robe commonly worn by men for daily modest clothing.'
    WHEN "name" = 'Shampoo' THEN 'Hair washing product used to clean and refresh hair.'
    WHEN "name" = 'Notebook' THEN 'Paper notebook for school, study notes, planning, or writing.'
    WHEN "name" = 'Pans' THEN 'Kitchen pan used for frying eggs, meat, vegetables, and other foods.'
    WHEN "name" = 'Frying Spatula' THEN 'Flat kitchen tool used for turning and lifting food while cooking.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Thobe%' THEN 'A long modest robe commonly worn by men for daily, formal, or Eid clothing.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Jubba%' THEN 'A loose modest robe worn by men for comfortable everyday or occasion wear.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Kurta%' THEN 'A long tunic-style top worn with modest outfits for casual or formal occasions.'
    WHEN "category"::text = 'CLOTHING' AND ("name" LIKE '%Shalwar Kameez%' OR "name" = 'Pakistani Eid Set') THEN 'Traditional matching outfit worn for modest daily wear, events, or Eid gatherings.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Waistcoat%' THEN 'Dress vest worn over a kurta or formal outfit for a sharper look.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Sherwani%' THEN 'Formal long coat worn for weddings, Eid, and special occasions.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Bisht%' THEN 'Traditional outer cloak worn over formal clothing for special occasions.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Ihram%' THEN 'Simple two-piece garment used by men during pilgrimage rituals.'
    WHEN "category"::text = 'CLOTHING' AND ("name" LIKE '%Kufi%' OR "name" LIKE '%Taqiyah%' OR "name" LIKE '%Cap%') THEN 'Small head covering worn with modest or traditional outfits.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Turban%' THEN 'Head wrap worn as part of traditional or modest styling.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Islamic Sandals%' THEN 'Open footwear suited for casual wear with modest traditional outfits.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Abaya%' THEN 'Loose full-length outer garment worn by women for modest everyday wear.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Jilbab%' THEN 'Loose modest garment designed to cover the body comfortably.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Khimar%' THEN 'Modest head and shoulder covering worn over everyday clothing.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Hijab%' THEN 'Headscarf worn for modest dressing and everyday styling.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Undercap%' THEN 'Soft cap worn under a hijab to help keep it secure.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Niqab%' THEN 'Face veil worn with modest clothing for additional coverage.'
    WHEN "category"::text = 'CLOTHING' AND ("name" LIKE '%Modest Dress%' OR "name" LIKE '%Eid Dress%') THEN 'Full-length dress designed for modest styling and special occasions.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Tunic%' THEN 'Long modest top worn with skirts, trousers, or loose pants.'
    WHEN "category"::text = 'CLOTHING' AND ("name" LIKE '%Loose Pants%' OR "name" LIKE '%Churidar%') THEN 'Comfortable modest pants worn with tunics, kurtas, or long tops.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Skirt%' THEN 'Long skirt designed for modest everyday outfits.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Prayer Dress%' THEN 'Loose garment worn for prayer and comfortable modest coverage.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Swimwear%' THEN 'Modest swim outfit designed for comfortable coverage in the water.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Dupatta%' THEN 'Long scarf worn with traditional outfits for modest styling.'
    WHEN "category"::text = 'CLOTHING' AND ("name" LIKE '%Shoes%' OR "name" LIKE '%Trainers%' OR "name" LIKE '%Sandals%' OR "name" LIKE '%Slippers%') THEN 'Footwear for everyday outfits, walking, school, or casual wear.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Socks%' THEN 'Soft socks worn with shoes for comfort and daily use.'
    WHEN "category"::text = 'CLOTHING' AND "name" LIKE '%Hats%' THEN 'Headwear used for sun protection, warmth, or casual styling.'
    WHEN "category"::text = 'CLOTHING' THEN 'Clothing item used for daily wear, modest outfits, or comfortable styling.'
    WHEN "category"::text = 'FRUIT_AND_VEGETABLES' AND "name" IN ('Parsley', 'Coriander', 'Mint') THEN "name" || ' used to add fresh flavour to salads, meals, and home cooking.'
    WHEN "category"::text = 'FRUIT_AND_VEGETABLES' THEN "name" || ' used for fresh eating, cooking, salads, snacks, or family meals.'
    WHEN "category"::text = 'BAKERY_AND_GRAINS' THEN "name" || ' used for meals, lunch boxes, breakfast, baking, or everyday pantry staples.'
    WHEN "category"::text = 'PANTRY_AND_COOKING' THEN "name" || ' used for cooking, seasoning, sauces, baking, or pantry storage.'
    WHEN "category"::text = 'DRINKS' THEN "name" || ' used as a drink for refreshment, meals, school, work, or travel.'
    WHEN "category"::text = 'MEAT_DAIRY_AND_PROTEIN' THEN "name" || ' used for cooking meals, adding protein, or preparing family dinners.'
    WHEN "category"::text = 'SNACKS_AND_SWEETS' THEN "name" || ' used as a snack, treat, lunch-box item, or quick dessert.'
    WHEN "category"::text = 'KITCHEN_AND_COOKWARE' THEN "name" || ' used for preparing, cooking, serving, or storing food at home.'
    WHEN "category"::text = 'CLEANING_AND_PERSONAL_CARE' THEN "name" || ' used for cleaning, hygiene, personal care, or household routines.'
    WHEN "category"::text = 'HOME_AND_STORAGE' THEN "name" || ' used for home organisation, comfort, storage, or everyday household needs.'
    WHEN "category"::text = 'ELECTRONICS' THEN "name" || ' used for communication, work, entertainment, charging, or digital tasks.'
    ELSE "name" || ' used for school, writing, organising, carrying items, or everyday errands.'
  END;
