import { ProductCategory } from "@prisma/client";

export type CatalogSourceItem = {
  name: string;
  unitLabel: string;
  basePrice: number;
  subcategory?: string;
};

export type CatalogSourceSection = {
  enumValue: ProductCategory;
  label: string;
  items: CatalogSourceItem[];
};

const dollars = (value: number) => Math.round(value * 100);

const muslimClothingMen = "Men's Muslim Clothing";
const muslimClothingWomen = "Women's Muslim Clothing";

export const CATALOG_SOURCE: CatalogSourceSection[] = [
  {
    enumValue: ProductCategory.FRUIT_AND_VEGETABLES,
    label: "Fruit & Vegetables",
    items: [
      { name: "Apples", basePrice: dollars(4.8), unitLabel: "per kg" },
      { name: "Bananas", basePrice: dollars(4.2), unitLabel: "per kg" },
      { name: "Oranges", basePrice: dollars(4.5), unitLabel: "per kg" },
      { name: "Mangoes", basePrice: dollars(5.9), unitLabel: "per kg" },
      { name: "Pineapples", basePrice: dollars(4.5), unitLabel: "each" },
      { name: "Strawberries", basePrice: dollars(4.9), unitLabel: "per punnet" },
      { name: "Blueberries", basePrice: dollars(5.5), unitLabel: "per punnet" },
      { name: "Avocados", basePrice: dollars(2.4), unitLabel: "each" },
      { name: "Carrots", basePrice: dollars(2.9), unitLabel: "per kg" },
      { name: "Tomatoes", basePrice: dollars(5.8), unitLabel: "per kg" },
      { name: "Potatoes", basePrice: dollars(3.1), unitLabel: "per kg" },
      { name: "Sweet Potato", basePrice: dollars(4.2), unitLabel: "per kg" },
      { name: "Onions", basePrice: dollars(2.4), unitLabel: "per kg" },
      { name: "Lettuce", basePrice: dollars(2.7), unitLabel: "each" },
      { name: "Broccoli", basePrice: dollars(3.9), unitLabel: "each" },
      { name: "Spinach", basePrice: dollars(3), unitLabel: "per bunch" },
      { name: "Corn", basePrice: dollars(1.4), unitLabel: "each" },
      { name: "Peas", basePrice: dollars(3.8), unitLabel: "per 500g" },
      { name: "Mushrooms", basePrice: dollars(4.3), unitLabel: "per punnet" },
      { name: "Cucumbers", basePrice: dollars(2.8), unitLabel: "each" },
      { name: "Capsicum", basePrice: dollars(3.2), unitLabel: "each" },
      { name: "Zucchini", basePrice: dollars(3.3), unitLabel: "per kg" },
      { name: "Eggplant", basePrice: dollars(4.1), unitLabel: "each" },
      { name: "Garlic", basePrice: dollars(1.8), unitLabel: "each" },
      { name: "Ginger", basePrice: dollars(3.6), unitLabel: "per kg" },
      { name: "Parsley", basePrice: dollars(2.5), unitLabel: "per bunch" },
      { name: "Coriander", basePrice: dollars(2.5), unitLabel: "per bunch" },
      { name: "Mint", basePrice: dollars(2.5), unitLabel: "per bunch" },
      { name: "Lemons", basePrice: dollars(0.9), unitLabel: "each" },
      { name: "Limes", basePrice: dollars(1.1), unitLabel: "each" },
    ],
  },
  {
    enumValue: ProductCategory.BAKERY_AND_GRAINS,
    label: "Bakery & Grains",
    items: [
      { name: "Bread", basePrice: dollars(2.4), unitLabel: "each" },
      { name: "Buns", basePrice: dollars(4.2), unitLabel: "per pack" },
      { name: "Rolls", basePrice: dollars(4.5), unitLabel: "per pack" },
      { name: "Wraps", basePrice: dollars(4.8), unitLabel: "per pack" },
      { name: "Flatbread", basePrice: dollars(3.8), unitLabel: "per pack" },
      { name: "Croissants", basePrice: dollars(6.5), unitLabel: "per pack" },
      { name: "Bagels", basePrice: dollars(5.5), unitLabel: "per pack" },
      { name: "Rice", basePrice: dollars(3.99), unitLabel: "per kg" },
      { name: "Brown Rice", basePrice: dollars(4.4), unitLabel: "per kg" },
      { name: "Basmati Rice", basePrice: dollars(5.2), unitLabel: "per kg" },
      { name: "Pasta", basePrice: dollars(1.1), unitLabel: "per 500g" },
      { name: "Flour", basePrice: dollars(1.3), unitLabel: "per kg" },
      { name: "Oats", basePrice: dollars(3.2), unitLabel: "per kg" },
      { name: "Quinoa", basePrice: dollars(8.5), unitLabel: "per 500g" },
      { name: "Couscous", basePrice: dollars(3.6), unitLabel: "per 500g" },
    ],
  },
  {
    enumValue: ProductCategory.PANTRY_AND_COOKING,
    label: "Pantry & Cooking",
    items: [
      { name: "Sugar", basePrice: dollars(1.8), unitLabel: "per kg" },
      { name: "Salt", basePrice: dollars(1), unitLabel: "per kg" },
      { name: "Cooking Oil", basePrice: dollars(4.8), unitLabel: "per L" },
      { name: "Honey", basePrice: dollars(6.2), unitLabel: "per kg" },
      { name: "Jam", basePrice: dollars(3.9), unitLabel: "per jar" },
      { name: "Peanut Butter", basePrice: dollars(5.2), unitLabel: "per jar" },
      { name: "Tomato Sauce", basePrice: dollars(3.2), unitLabel: "per bottle" },
      { name: "BBQ Sauce", basePrice: dollars(3.4), unitLabel: "per bottle" },
      { name: "Soy Sauce", basePrice: dollars(3.6), unitLabel: "per bottle" },
      { name: "Pepper", basePrice: dollars(2.8), unitLabel: "per jar" },
      { name: "Paprika", basePrice: dollars(3.1), unitLabel: "per jar" },
      { name: "Turmeric", basePrice: dollars(3.2), unitLabel: "per jar" },
      { name: "Cumin", basePrice: dollars(3.4), unitLabel: "per jar" },
      { name: "Stock Cubes", basePrice: dollars(2.4), unitLabel: "per pack" },
      { name: "Vinegar", basePrice: dollars(2.9), unitLabel: "per bottle" },
      { name: "Canned Beans", basePrice: dollars(1.4), unitLabel: "per can" },
      { name: "Canned Corn", basePrice: dollars(1.6), unitLabel: "per can" },
      { name: "Canned Tuna", basePrice: dollars(2.2), unitLabel: "per can" },
    ],
  },
  {
    enumValue: ProductCategory.DRINKS,
    label: "Drinks",
    items: [
      { name: "Water", basePrice: dollars(1.8), unitLabel: "per L" },
      { name: "Juice", basePrice: dollars(3.8), unitLabel: "per L" },
      { name: "Milk", basePrice: dollars(1.6), unitLabel: "per L" },
      { name: "Flavoured Milk", basePrice: dollars(4.2), unitLabel: "per L" },
      { name: "Chocolate Milk", basePrice: dollars(3.9), unitLabel: "per L" },
      { name: "Iced Coffee", basePrice: dollars(4.5), unitLabel: "each" },
      { name: "Sports Drink", basePrice: dollars(3.6), unitLabel: "each" },
      { name: "Coconut Water", basePrice: dollars(4.2), unitLabel: "per L" },
      { name: "Soda", basePrice: dollars(2.9), unitLabel: "per L" },
      { name: "Coffee", basePrice: dollars(5.9), unitLabel: "per pack" },
      { name: "Tea", basePrice: dollars(3.8), unitLabel: "per box" },
      { name: "Energy Drink", basePrice: dollars(3.9), unitLabel: "each" },
      { name: "Sparkling Water", basePrice: dollars(2.7), unitLabel: "per L" },
    ],
  },
  {
    enumValue: ProductCategory.MEAT_DAIRY_AND_PROTEIN,
    label: "Meat, Dairy & Protein",
    items: [
      { name: "Eggs", basePrice: dollars(6.5), unitLabel: "per dozen" },
      { name: "Chicken", basePrice: dollars(13.7), unitLabel: "per kg" },
      { name: "Chicken Mince", basePrice: dollars(11.5), unitLabel: "per kg" },
      { name: "Frozen Chicken Tenders", basePrice: dollars(9.8), unitLabel: "per pack" },
      { name: "Frozen Chicken Nuggets", basePrice: dollars(8.9), unitLabel: "per pack" },
      { name: "Beef", basePrice: dollars(21.99), unitLabel: "per kg" },
      { name: "Beef Mince", basePrice: dollars(12.5), unitLabel: "per kg" },
      { name: "Fish", basePrice: dollars(15.4), unitLabel: "per kg" },
      { name: "Cheese", basePrice: dollars(9.9), unitLabel: "per kg" },
      { name: "Yogurt", basePrice: dollars(4.8), unitLabel: "per tub" },
      { name: "Butter", basePrice: dollars(4.9), unitLabel: "per pack" },
      { name: "Cream", basePrice: dollars(3.2), unitLabel: "per tub" },
      { name: "Paneer", basePrice: dollars(5.9), unitLabel: "per pack" },
      { name: "Sausages", basePrice: dollars(8.2), unitLabel: "per kg" },
      { name: "Lamb", basePrice: dollars(11), unitLabel: "per kg" },
      { name: "Lamb Chops", basePrice: dollars(22.5), unitLabel: "per kg" },
      { name: "Lamb Shoulder", basePrice: dollars(16.9), unitLabel: "per kg" },
      { name: "Lamb Leg", basePrice: dollars(18.5), unitLabel: "per kg" },
      { name: "Tofu", basePrice: dollars(4.2), unitLabel: "per pack" },
    ],
  },
  {
    enumValue: ProductCategory.SNACKS_AND_SWEETS,
    label: "Snacks & Sweets",
    items: [
      { name: "Chips", basePrice: dollars(2.8), unitLabel: "per pack" },
      { name: "Biscuits", basePrice: dollars(2.5), unitLabel: "per pack" },
      { name: "Crackers", basePrice: dollars(2.9), unitLabel: "per pack" },
      { name: "Instant Noodles", basePrice: dollars(1.9), unitLabel: "per pack" },
      { name: "Chocolate", basePrice: dollars(2.9), unitLabel: "per bar" },
      { name: "Candy", basePrice: dollars(2.2), unitLabel: "per pack" },
      { name: "Gummies", basePrice: dollars(2.8), unitLabel: "per pack" },
      { name: "Wafers", basePrice: dollars(3.2), unitLabel: "per pack" },
      { name: "Granola Bars", basePrice: dollars(4.5), unitLabel: "per box" },
      { name: "Protein Bars", basePrice: dollars(8.5), unitLabel: "per box" },
      { name: "Snack Packs", basePrice: dollars(5.9), unitLabel: "per pack" },
      { name: "Ice Cream", basePrice: dollars(5.8), unitLabel: "per tub" },
      { name: "Cake", basePrice: dollars(7.9), unitLabel: "each" },
      { name: "Cookies", basePrice: dollars(3.9), unitLabel: "per pack" },
      { name: "Brownies", basePrice: dollars(4.8), unitLabel: "per pack" },
      { name: "Muffins", basePrice: dollars(3.9), unitLabel: "per pack" },
      { name: "Donuts", basePrice: dollars(3.8), unitLabel: "per pack" },
      { name: "Lollies", basePrice: dollars(2.4), unitLabel: "per 100g" },
      { name: "Popcorn", basePrice: dollars(1.8), unitLabel: "per pack" },
    ],
  },
  {
    enumValue: ProductCategory.KITCHEN_AND_COOKWARE,
    label: "Kitchen & Cookware",
    items: [
      { name: "Plates", basePrice: dollars(10), unitLabel: "each" },
      { name: "Bowls", basePrice: dollars(8), unitLabel: "each" },
      { name: "Cups", basePrice: dollars(6), unitLabel: "each" },
      { name: "Spoons", basePrice: dollars(5), unitLabel: "per set" },
      { name: "Forks", basePrice: dollars(5), unitLabel: "per set" },
      { name: "Knives", basePrice: dollars(7), unitLabel: "per set" },
      { name: "Pots", basePrice: dollars(20), unitLabel: "each" },
      { name: "Pans", basePrice: dollars(25), unitLabel: "each" },
      { name: "Frying Spatula", basePrice: dollars(6.5), unitLabel: "each" },
      { name: "Tongs", basePrice: dollars(7.5), unitLabel: "each" },
      { name: "Ladle", basePrice: dollars(6.8), unitLabel: "each" },
      { name: "Food Containers", basePrice: dollars(12.5), unitLabel: "per set" },
      { name: "Lunch Containers", basePrice: dollars(9.9), unitLabel: "per set" },
      { name: "Water Jugs", basePrice: dollars(11.5), unitLabel: "each" },
      { name: "Cutting Board", basePrice: dollars(12), unitLabel: "each" },
      { name: "Measuring Cups", basePrice: dollars(10), unitLabel: "per set" },
    ],
  },
  {
    enumValue: ProductCategory.CLEANING_AND_PERSONAL_CARE,
    label: "Cleaning & Personal Care",
    items: [
      { name: "Soap", basePrice: dollars(1.9), unitLabel: "each" },
      { name: "Shampoo", basePrice: dollars(5.5), unitLabel: "each" },
      { name: "Conditioner", basePrice: dollars(5.5), unitLabel: "each" },
      { name: "Face Wash", basePrice: dollars(6.9), unitLabel: "each" },
      { name: "Body Wash", basePrice: dollars(6.5), unitLabel: "each" },
      { name: "Lotion", basePrice: dollars(7.5), unitLabel: "each" },
      { name: "Sunscreen", basePrice: dollars(11.9), unitLabel: "each" },
      { name: "Wet Wipes", basePrice: dollars(3.2), unitLabel: "per pack" },
      { name: "Toothpaste", basePrice: dollars(2.8), unitLabel: "each" },
      { name: "Toothbrush", basePrice: dollars(2.9), unitLabel: "each" },
      { name: "Tissues", basePrice: dollars(2.8), unitLabel: "per box" },
      { name: "Detergent", basePrice: dollars(9.9), unitLabel: "per L" },
      { name: "Dishwashing Liquid", basePrice: dollars(3.8), unitLabel: "per L" },
      { name: "Cleaning Spray", basePrice: dollars(4.2), unitLabel: "each" },
      { name: "Mop", basePrice: dollars(16.5), unitLabel: "each" },
      { name: "Broom", basePrice: dollars(12.9), unitLabel: "each" },
      { name: "Deodorant", basePrice: dollars(4.9), unitLabel: "each" },
      { name: "Hand Sanitizer", basePrice: dollars(2.9), unitLabel: "each" },
    ],
  },
  {
    enumValue: ProductCategory.CLOTHING,
    label: "Clothing",
    items: [
      { name: "T-Shirts", basePrice: dollars(14.99), unitLabel: "each" },
      { name: "Pants", basePrice: dollars(29.99), unitLabel: "each" },
      { name: "Shorts", basePrice: dollars(19.99), unitLabel: "each" },
      { name: "Hoodies", basePrice: dollars(39.99), unitLabel: "each" },
      { name: "Jackets", basePrice: dollars(59.99), unitLabel: "each" },
      { name: "Socks", basePrice: dollars(9.99), unitLabel: "per pack" },
      { name: "Hats", basePrice: dollars(11.99), unitLabel: "each" },
      { name: "Sweaters", basePrice: dollars(34.99), unitLabel: "each" },
      { name: "Formal Shoes", basePrice: dollars(79.99), unitLabel: "per pair" },
      { name: "Trainers", basePrice: dollars(69.99), unitLabel: "per pair" },
      { name: "Sandals", basePrice: dollars(34.5), unitLabel: "per pair" },
      { name: "Slippers", basePrice: dollars(19.99), unitLabel: "per pair" },
      { name: "Pajamas", basePrice: dollars(32.5), unitLabel: "each" },
      { name: "Sportswear Set", basePrice: dollars(49.99), unitLabel: "each" },
      { name: "School Uniform", basePrice: dollars(44.5), unitLabel: "each" },
      { name: "Basic Thobe", basePrice: dollars(39.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Premium Thobe", basePrice: dollars(89.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Embroidered Thobe", basePrice: dollars(109.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Slim Fit Thobe", basePrice: dollars(59.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Saudi Style Thobe", basePrice: dollars(74.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Moroccan Hooded Jubba", basePrice: dollars(69.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Classic Jubba", basePrice: dollars(44.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Premium Jubba", basePrice: dollars(79.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Embroidered Jubba", basePrice: dollars(99.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Short Kurta", basePrice: dollars(29.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Long Kurta", basePrice: dollars(39.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Formal Kurta", basePrice: dollars(64.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Embroidered Kurta", basePrice: dollars(59.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Casual Shalwar Kameez", basePrice: dollars(44.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Basic Shalwar Kameez", basePrice: dollars(34.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Formal Shalwar Kameez", basePrice: dollars(74.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Embroidered Shalwar Kameez", basePrice: dollars(94.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Eid Shalwar Kameez", basePrice: dollars(84.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Waistcoat for Kurta", basePrice: dollars(69.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Men's Waistcoat", basePrice: dollars(69.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Formal Sherwani", basePrice: dollars(159.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Wedding Sherwani", basePrice: dollars(189.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Bisht", basePrice: dollars(149.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Premium Bisht", basePrice: dollars(179.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Ihram Set", basePrice: dollars(39.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Kufi", basePrice: dollars(14.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Taqiyah", basePrice: dollars(12.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Simple Kufi Cap", basePrice: dollars(11.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Imamah Turban", basePrice: dollars(29.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Cotton Turban Wrap", basePrice: dollars(24.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Islamic Sandals", basePrice: dollars(39.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Leather Islamic Sandals", basePrice: dollars(69.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Kids Thobe", basePrice: dollars(34.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Kids Premium Thobe", basePrice: dollars(49.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Kids Kurta", basePrice: dollars(29.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Kids Shalwar Kameez", basePrice: dollars(39.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Eid Thobe", basePrice: dollars(79.99), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Pakistani Eid Set", basePrice: dollars(84.5), unitLabel: "each", subcategory: muslimClothingMen },
      { name: "Basic Abaya", basePrice: dollars(49.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Premium Abaya", basePrice: dollars(99.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Embroidered Abaya", basePrice: dollars(124.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Open Front Abaya", basePrice: dollars(74.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Butterfly Abaya", basePrice: dollars(89.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "One Piece Jilbab", basePrice: dollars(54.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Two Piece Jilbab", basePrice: dollars(69.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Jilbab", basePrice: dollars(54.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Short Khimar", basePrice: dollars(29.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Long Khimar", basePrice: dollars(39.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Khimar", basePrice: dollars(34.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Basic Hijab", basePrice: dollars(12.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Premium Hijab", basePrice: dollars(24.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Silk Hijab", basePrice: dollars(32.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Jersey Hijab", basePrice: dollars(19.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Chiffon Hijab", basePrice: dollars(17.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Undercap", basePrice: dollars(8.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Cotton Undercap", basePrice: dollars(9.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Simple Niqab", basePrice: dollars(19.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Two Layer Niqab", basePrice: dollars(24.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Modest Dress", basePrice: dollars(64.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Premium Modest Dress", basePrice: dollars(99.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Long Tunic", basePrice: dollars(42.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Embroidered Long Tunic", basePrice: dollars(69.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Loose Pants", basePrice: dollars(36.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Wide Leg Loose Pants", basePrice: dollars(44.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Long Skirt", basePrice: dollars(39.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Pleated Long Skirt", basePrice: dollars(49.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Prayer Dress", basePrice: dollars(39.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Premium Prayer Dress", basePrice: dollars(59.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Modest Swimwear", basePrice: dollars(89.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Premium Modest Swimwear", basePrice: dollars(129.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Eid Dress", basePrice: dollars(89.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Embroidered Eid Dress", basePrice: dollars(119.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Dupatta", basePrice: dollars(19.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Churidar Pants", basePrice: dollars(26.5), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Kids Hijab", basePrice: dollars(9.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Kids Abaya", basePrice: dollars(34.99), unitLabel: "each", subcategory: muslimClothingWomen },
      { name: "Kids Prayer Dress", basePrice: dollars(29.99), unitLabel: "each", subcategory: muslimClothingWomen },
    ],
  },
  {
    enumValue: ProductCategory.HOME_AND_STORAGE,
    label: "Home & Storage",
    items: [
      { name: "Towels", basePrice: dollars(14.99), unitLabel: "each" },
      { name: "Blankets", basePrice: dollars(39.99), unitLabel: "each" },
      { name: "Pillows", basePrice: dollars(19.99), unitLabel: "each" },
      { name: "Storage Boxes", basePrice: dollars(11.99), unitLabel: "each" },
      { name: "Storage Shelves", basePrice: dollars(49.99), unitLabel: "each" },
      { name: "Laundry Basket", basePrice: dollars(18.5), unitLabel: "each" },
      { name: "Bedside Table", basePrice: dollars(59.99), unitLabel: "each" },
      { name: "Shoe Rack", basePrice: dollars(34.5), unitLabel: "each" },
      { name: "Table Covers", basePrice: dollars(16.99), unitLabel: "each" },
      { name: "Curtains", basePrice: dollars(39.5), unitLabel: "per set" },
      { name: "Hangers", basePrice: dollars(7.99), unitLabel: "per pack" },
    ],
  },
  {
    enumValue: ProductCategory.ELECTRONICS,
    label: "Electronics",
    items: [
      { name: "Phone", basePrice: dollars(799), unitLabel: "each" },
      { name: "Tablet", basePrice: dollars(499), unitLabel: "each" },
      { name: "Laptop", basePrice: dollars(1199), unitLabel: "each" },
      { name: "Headphones", basePrice: dollars(99), unitLabel: "each" },
      { name: "Charger", basePrice: dollars(19.99), unitLabel: "each" },
      { name: "Power Bank", basePrice: dollars(39.99), unitLabel: "each" },
      { name: "USB Cable", basePrice: dollars(12.99), unitLabel: "each" },
      { name: "Mouse", basePrice: dollars(24.99), unitLabel: "each" },
      { name: "Keyboard", basePrice: dollars(39.99), unitLabel: "each" },
      { name: "Small Speakers", basePrice: dollars(49.5), unitLabel: "per pair" },
    ],
  },
  {
    enumValue: ProductCategory.SCHOOL_AND_MISC,
    label: "School & Misc",
    items: [
      { name: "Notebook", basePrice: dollars(2.9), unitLabel: "each" },
      { name: "Pen", basePrice: dollars(1.8), unitLabel: "each" },
      { name: "Pencil", basePrice: dollars(1), unitLabel: "each" },
      { name: "Eraser", basePrice: dollars(1), unitLabel: "each" },
      { name: "Highlighters", basePrice: dollars(4.5), unitLabel: "per pack" },
      { name: "Markers", basePrice: dollars(5.9), unitLabel: "per pack" },
      { name: "Ruler", basePrice: dollars(1.8), unitLabel: "each" },
      { name: "Geometry Set", basePrice: dollars(4.9), unitLabel: "per set" },
      { name: "Sticky Notes", basePrice: dollars(3.2), unitLabel: "per pack" },
      { name: "Backpack", basePrice: dollars(24.99), unitLabel: "each" },
      { name: "Bottle", basePrice: dollars(9.99), unitLabel: "each" },
      { name: "Umbrella", basePrice: dollars(14.99), unitLabel: "each" },
      { name: "Shopping Bag", basePrice: dollars(4.99), unitLabel: "each" },
      { name: "Lunch Box", basePrice: dollars(11.99), unitLabel: "each" },
    ],
  },
];
