import { BotPersonality, ProductCategory } from "@prisma/client";

export type CatalogProduct = {
  sku: string;
  name: string;
  category: ProductCategory;
  description: string;
  basePrice: number;
  supplierPrice: number;
  demandScore: number;
  popularityScore: number;
  trendLabel: string;
  spoilable: boolean;
  shelfLife?: number;
  keywords: string[];
  imageUrl?: string;
};

export const PRODUCT_CATALOG: CatalogProduct[] = [
  {
    sku: "food-apples",
    name: "Apples",
    category: ProductCategory.FOOD,
    description: "Crisp everyday apples sold in single units for snackers and lunchboxes.",
    basePrice: 180,
    supplierPrice: 110,
    demandScore: 1.18,
    popularityScore: 1.21,
    trendLabel: "High demand",
    spoilable: true,
    shelfLife: 120,
    keywords: ["apple", "fruit", "fresh", "snack", "cheap apples"],
  },
  {
    sku: "food-bananas",
    name: "Bananas",
    category: ProductCategory.FOOD,
    description: "Soft yellow bananas with steady family demand.",
    basePrice: 150,
    supplierPrice: 90,
    demandScore: 1.1,
    popularityScore: 1.12,
    trendLabel: "Trending",
    spoilable: true,
    shelfLife: 96,
    keywords: ["banana", "fruit", "breakfast", "smoothie"],
  },
  {
    sku: "food-bread",
    name: "Bread Loaves",
    category: ProductCategory.FOOD,
    description: "Classic sandwich bread with reliable repeat purchases.",
    basePrice: 320,
    supplierPrice: 220,
    demandScore: 1.08,
    popularityScore: 1.04,
    trendLabel: "Stable",
    spoilable: true,
    shelfLife: 72,
    keywords: ["bread", "bakery", "sandwich", "toast"],
  },
  {
    sku: "food-tomatoes",
    name: "Tomatoes",
    category: ProductCategory.FOOD,
    description: "Fresh tomatoes for sandwiches, salads, and cooking.",
    basePrice: 210,
    supplierPrice: 130,
    demandScore: 1.06,
    popularityScore: 1.08,
    trendLabel: "Fresh pick",
    spoilable: true,
    shelfLife: 84,
    keywords: ["tomato", "fresh tomatoes", "salad", "produce"],
  },
  {
    sku: "food-rice",
    name: "Rice",
    category: ProductCategory.FOOD,
    description: "Bagged rice staple with dependable repeat demand.",
    basePrice: 550,
    supplierPrice: 390,
    demandScore: 0.96,
    popularityScore: 1.01,
    trendLabel: "Stable",
    spoilable: false,
    keywords: ["rice", "staple", "grains", "bulk"],
  },
  {
    sku: "food-eggs",
    name: "Eggs",
    category: ProductCategory.FOOD,
    description: "Carton of eggs for breakfast and baking.",
    basePrice: 620,
    supplierPrice: 470,
    demandScore: 1.14,
    popularityScore: 1.09,
    trendLabel: "Breakfast rush",
    spoilable: true,
    shelfLife: 144,
    keywords: ["eggs", "breakfast", "baking", "protein"],
  },
  {
    sku: "food-chips",
    name: "Chips",
    category: ProductCategory.FOOD,
    description: "Crunchy snack bags that move quickly during evening browsing.",
    basePrice: 280,
    supplierPrice: 170,
    demandScore: 1.12,
    popularityScore: 1.2,
    trendLabel: "Popular",
    spoilable: false,
    keywords: ["chips", "snacks", "crisps", "party"],
  },
  {
    sku: "drink-water",
    name: "Water",
    category: ProductCategory.DRINKS,
    description: "Bottled water with broad everyday demand.",
    basePrice: 190,
    supplierPrice: 100,
    demandScore: 1.25,
    popularityScore: 1.22,
    trendLabel: "Heatwave boost",
    spoilable: false,
    keywords: ["water", "drink", "hydration", "cheap drink"],
  },
  {
    sku: "drink-juice",
    name: "Juice",
    category: ProductCategory.DRINKS,
    description: "Fruit juice cartons for breakfast and lunchboxes.",
    basePrice: 360,
    supplierPrice: 230,
    demandScore: 1.2,
    popularityScore: 1.14,
    trendLabel: "Trending",
    spoilable: true,
    shelfLife: 168,
    keywords: ["juice", "fruit drink", "breakfast", "fresh juice"],
  },
  {
    sku: "drink-milk",
    name: "Milk",
    category: ProductCategory.DRINKS,
    description: "Household milk sold in standard cartons.",
    basePrice: 410,
    supplierPrice: 280,
    demandScore: 1.03,
    popularityScore: 1.02,
    trendLabel: "Steady",
    spoilable: true,
    shelfLife: 96,
    keywords: ["milk", "dairy", "breakfast", "coffee"],
  },
  {
    sku: "kitchen-plates",
    name: "Plates",
    category: ProductCategory.KITCHEN,
    description: "Simple dinner plates for home kitchens and student setups.",
    basePrice: 740,
    supplierPrice: 510,
    demandScore: 0.9,
    popularityScore: 0.95,
    trendLabel: "Low demand",
    spoilable: false,
    keywords: ["plates", "dishes", "kitchen accessories"],
  },
  {
    sku: "kitchen-cups",
    name: "Cups",
    category: ProductCategory.KITCHEN,
    description: "Versatile drinking cups in everyday bundles.",
    basePrice: 540,
    supplierPrice: 360,
    demandScore: 0.98,
    popularityScore: 1.0,
    trendLabel: "Stable",
    spoilable: false,
    keywords: ["cups", "drinkware", "kitchen", "mugs"],
  },
  {
    sku: "kitchen-spoons",
    name: "Spoons",
    category: ProductCategory.KITCHEN,
    description: "Cutlery basics for quick kitchen restocks.",
    basePrice: 430,
    supplierPrice: 290,
    demandScore: 0.94,
    popularityScore: 0.97,
    trendLabel: "Steady",
    spoilable: false,
    keywords: ["spoons", "cutlery", "utensils", "kitchen tools"],
  },
  {
    sku: "kitchen-knives",
    name: "Knives",
    category: ProductCategory.KITCHEN,
    description: "Basic kitchen knives suitable for food prep.",
    basePrice: 980,
    supplierPrice: 690,
    demandScore: 0.88,
    popularityScore: 0.9,
    trendLabel: "Selective demand",
    spoilable: false,
    keywords: ["knives", "kitchen knife", "prep", "utensils"],
  },
  {
    sku: "clothes-tshirts",
    name: "T-Shirts",
    category: ProductCategory.CLOTHES,
    description: "Simple everyday tees in general sizing.",
    basePrice: 890,
    supplierPrice: 610,
    demandScore: 1.04,
    popularityScore: 1.08,
    trendLabel: "Popular basics",
    spoilable: false,
    keywords: ["tshirts", "shirts", "clothes", "casual"],
  },
  {
    sku: "clothes-socks",
    name: "Socks",
    category: ProductCategory.CLOTHES,
    description: "Multi-use socks that sell steadily and in bundles.",
    basePrice: 390,
    supplierPrice: 240,
    demandScore: 1.09,
    popularityScore: 1.05,
    trendLabel: "Reliable seller",
    spoilable: false,
    keywords: ["socks", "clothing", "essentials", "daily wear"],
  },
  {
    sku: "clothes-hats",
    name: "Hats",
    category: ProductCategory.CLOTHES,
    description: "Casual hats for sunny days and fashion shoppers.",
    basePrice: 760,
    supplierPrice: 500,
    demandScore: 0.93,
    popularityScore: 0.98,
    trendLabel: "Seasonal",
    spoilable: false,
    keywords: ["hats", "cap", "clothes", "fashion"],
  },
  {
    sku: "essentials-soap",
    name: "Soap",
    category: ProductCategory.ESSENTIALS,
    description: "Daily-use soap bars with dependable household demand.",
    basePrice: 260,
    supplierPrice: 150,
    demandScore: 1.05,
    popularityScore: 1.03,
    trendLabel: "Steady",
    spoilable: false,
    keywords: ["soap", "daily essentials", "cleaning", "bath"],
  },
  {
    sku: "essentials-tissues",
    name: "Tissues",
    category: ProductCategory.ESSENTIALS,
    description: "Soft tissue boxes bought regularly for homes and desks.",
    basePrice: 300,
    supplierPrice: 180,
    demandScore: 1.07,
    popularityScore: 1.06,
    trendLabel: "Useful pick",
    spoilable: false,
    keywords: ["tissues", "paper", "daily essentials", "home care"],
  },
];

export const SHOP_THEMES = [
  { label: "Forest", value: "#2D6A4F" },
  { label: "Sunset", value: "#C96C50" },
  { label: "Ocean", value: "#1D4ED8" },
  { label: "Coral", value: "#E76F51" },
  { label: "Gold", value: "#D4A017" },
] as const;

export const INITIAL_USERS = [
  {
    username: "avery",
    email: "avery@bazaarly.local",
    displayName: "Avery",
    balance: 28400,
    shop: {
      name: "Fresh Basket Co",
      slug: "fresh-basket-co",
      description: "Fast-moving produce and breakfast staples with sharp prices.",
      categoryFocus: ProductCategory.FOOD,
      accentColor: "#2D6A4F",
      rating: 4.6,
      totalSales: 34,
      totalRevenue: 18240,
    },
  },
  {
    username: "jordan",
    email: "jordan@bazaarly.local",
    displayName: "Jordan",
    balance: 25150,
    shop: {
      name: "Sip Street",
      slug: "sip-street",
      description: "Cold drinks, lunchbox staples, and convenient bundles.",
      categoryFocus: ProductCategory.DRINKS,
      accentColor: "#1D4ED8",
      rating: 4.4,
      totalSales: 29,
      totalRevenue: 16070,
    },
  },
  {
    username: "mia",
    email: "mia@bazaarly.local",
    displayName: "Mia",
    balance: 23920,
    shop: {
      name: "Homeware Nook",
      slug: "homeware-nook",
      description: "Kitchen basics and household small goods for practical shoppers.",
      categoryFocus: ProductCategory.KITCHEN,
      accentColor: "#C96C50",
      rating: 4.3,
      totalSales: 18,
      totalRevenue: 11440,
    },
  },
  {
    username: "noah",
    email: "noah@bazaarly.local",
    displayName: "Noah",
    balance: 26270,
    shop: {
      name: "Daily Thread",
      slug: "daily-thread",
      description: "Simple clothes and daily essentials with consistent stock.",
      categoryFocus: ProductCategory.CLOTHES,
      accentColor: "#D4A017",
      rating: 4.2,
      totalSales: 21,
      totalRevenue: 12890,
    },
  },
] as const;

export const INITIAL_BOTS = [
  {
    displayName: "Penny Saver",
    type: BotPersonality.BUDGET,
    budget: 1800,
    preferenceCategory: ProductCategory.FOOD,
    activityLevel: 75,
  },
  {
    displayName: "Quality Quinn",
    type: BotPersonality.QUALITY,
    budget: 3200,
    preferenceCategory: ProductCategory.DRINKS,
    activityLevel: 60,
  },
  {
    displayName: "Loyal Lee",
    type: BotPersonality.LOYAL,
    budget: 2600,
    preferenceCategory: ProductCategory.ESSENTIALS,
    activityLevel: 68,
  },
  {
    displayName: "Bulk Brooke",
    type: BotPersonality.BULK,
    budget: 4800,
    preferenceCategory: ProductCategory.FOOD,
    activityLevel: 52,
  },
  {
    displayName: "Random Riley",
    type: BotPersonality.RANDOM,
    budget: 2400,
    preferenceCategory: ProductCategory.KITCHEN,
    activityLevel: 58,
  },
] as const;
